### ISSUE TITLE
Detached threads leak return memory (pthread)

### ISSUE THREAD

**Issue by edenhill** [tinycthread/tinycthread#24]
`_thrd_wrapper_function` allocates space for the thread function's returned integer, this pointer is later freed in `thrd_join()`.
But in the case where the thread is detached `thrd_join()` will never be called and thus results in a small portion of leaked memory.
Not a big deal but it causes programs to fail valgrind cleanlyness.

**Comment by nemequ** [comment]
270ba1a09da3fe141e094d4837f0844ca683b336
