### ISSUE TITLE
cnd_timedwait not work correctly in Win32

### ISSUE THREAD

**Issue by zhuyie** [tinycthread/tinycthread#27]
int cnd_timedwait(cnd_t *cond, mtx_t *mtx, const struct timespec *ts)
{
#if defined(_TTHREAD_WIN32_)
  struct timespec now;
  if (timespec_get(&now, TIME_UTC) == 0)
  {
    DWORD delta = (DWORD)((ts->tv_sec - now.tv_sec) * 1000 +
                  (ts->tv_nsec - now.tv_nsec + 500000) / 1000000);
    return _cnd_timedwait_win32(cond, mtx, delta);
  }
  else
    return thrd_error;
#else
  ...
}

if timespec_get success, it will return the base, which is TIME_UTC(1).

**Comment by nemequ** [comment]
I don't have access to a Windows machine at the moment—just to confirm, does this work as expected?

```diff
diff --git a/source/tinycthread.c b/source/tinycthread.c
index 5464313..427967c 100644
--- a/source/tinycthread.c
+++ b/source/tinycthread.c
@@ -443,7 +443,7 @@ int cnd_timedwait(cnd_t *cond, mtx_t *mtx, const struct timespec *ts)
 {
 #if defined(_TTHREAD_WIN32_)
   struct timespec now;
-  if (timespec_get(&now, TIME_UTC) == 0)
+  if (timespec_get(&now, TIME_UTC) != 0)
   {
     DWORD delta = (DWORD)((ts->tv_sec - now.tv_sec) * 1000 +
                   (ts->tv_nsec - now.tv_nsec + 500000) / 1000000);
```

**Comment by zhuyie** [comment]
Yes, it will work. but i prefer this: 
if (timespec_get(&now, TIME_UTC) == TIME_UTC)
