### ISSUE TITLE
Warning conversion from DWORD ('unsigned long')  to int

### ISSUE THREAD

**Issue by thradams** [tinycthread/tinycthread#33]
See the 'result' variable

#if defined(_TTHREAD_WIN32_)
    static int _cnd_timedwait_win32(cnd_t *cond, mtx_t *mtx, DWORD timeout)
    {
        int result, lastWaiter;
....
      result = WaitForMultipleObjects(2, cond->mEvents, FALSE, timeout);

--x--
types are mixed
 else if (result == (int) WAIT_FAILED)

My sugestion is to use the native type DWORD.

**Comment by nemequ** [comment]
I don't have a good way to test Windows (I should really get AppVeyor set up for this repo)…  Does d2e74ba (pushed to the staging branch) work for you?

**Comment by thradams** [comment]
I did a pull request.
