### ISSUE TITLE
CreateThread vs. _beginthreadex

### ISSUE THREAD

**Issue by AndreasMartin72** [tinycthread/tinycthread#37]
Hello,

MSVC recommends to use _beginthreadex instead of CreateThread. In your project tinythreadpp you do, why not here?

Kindly reagrds,
Andreas

**Comment by nemequ** [comment]
https://msdn.microsoft.com/en-us/library/kdzttdcb(v=vs.120).aspx:

> This API cannot be used in applications that execute in the Windows Runtime or are compiled by using the clr:pure switch. For more information, see CRT functions not supported with /ZW.

Apparently VS 2015 fixed that (the warning box is gone), but not everyone is using VS 2015.  AFAICT CreateThread should work more reliably across various versions of Windows and Visual Studio.
