### ISSUE TITLE
compile error with MinGW

### ISSUE THREAD

**Issue by san-chang** [tinycthread/tinycthread#41]
## SYSTEM ENV
*windows 10*
*cmake version 3.7.0-rc2*
*gcc <GCC> 5.3.0 target mingw32*
## Description
I have some trouble in use "tiny c thread", I cloned this project from github today(branch master), but I can't build it in my computer (with MinGW).
### when building tinycthread.c gcc said 
`645:10 warning : implicit declaration of function 'GetThreadId'`
`880:3   warning : implicit declaration of function '_ftime_s'`
### when linking test-tinycthread.exe. ld return a exit status
`undefined reference to 'GetThreadId'`
`undefined reference to '_ftime_s'`

---
    I also have a visual studio 2015 community installed in my computer
    and It's worked(build completed) but there are some warning in test.c
    I try to run test-tinycthread.exe and all test passed.

## CMake info
    -- The C compiler identification is GNU 5.3.0
    -- The CXX compiler identification is GNU 5.3.0
    -- Check for working C compiler: C:/MinGW/bin/gcc.exe
    -- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/MinGW/bin/g++.exe
    -- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/xx/test/tinycthread/build
## make info
    Scanning dependencies of target tinycthread
    [ 25%] Building C object CMakeFiles/tinycthread.dir/source/tinycthread.c.obj
    c:/Users/xx/test/tinycthread/source/tinycthread.c: In function 'thrd_equal':
    c:/Users/xx/test/tinycthread/source/tinycthread.c:645:10: warning: implicit declaration of function 'GetThreadId' [-Wimplicit-function-declaration]
       return GetThreadId(thr0) == GetThreadId(thr1);
              ^
    c:/Users/xx/test/tinycthread/source/tinycthread.c: In function '_tthread_timespec_get':
    c:/Users/xx/test/tinycthread/source/tinycthread.c:880:3: warning: implicit declaration of function '_ftime_s' [-Wimplicit-function-declaration]
       _ftime_s(&tb);
       ^
    [ 50%] Linking C static library libtinycthread.a
    [ 50%] Built target tinycthread
    Scanning dependencies of target test-tinycthread
    [ 75%] Building C object CMakeFiles/test-tinycthread.dir/test/test.c.obj
    [100%] Linking C executable test-tinycthread.exe
    libtinycthread.a(tinycthread.c.obj):tinycthread.c:(.text+0x95b): undefined reference to `GetThreadId'
    libtinycthread.a(tinycthread.c.obj):tinycthread.c:(.text+0x968): undefined reference to `GetThreadId'
    libtinycthread.a(tinycthread.c.obj):tinycthread.c:(.text+0xd80): undefined reference to `_ftime_s'
    collect2.exe: error: ld returned 1 exit status
    make[2]: *** [test-tinycthread.exe] Error 1
    make[1]: *** [CMakeFiles/test-tinycthread.dir/all] Error 2
    make: *** [all] Error 2

**Comment by praisethemoon** [comment]
Hello, I'm also having this error. My project compiles perfectly with Visual Studio & Clang on Windows, and Clang & Gcc on Linux & Mac. The only issue I'm having is with MinGW because of this error. Not sure if it's MinGW or tinycthreads related. +1

**Comment by MarcusJohnson91** [comment]
Well MinGW uses GCC, and probably an old version at that. so update gcc.

**Comment by holywyvern** [comment]
@praisethemoon Try using MinGW-w64, it's updated more regularly. Also it can compile for x86-x64

**Comment by praisethemoon** [comment]
@holywyvern You are awesome.

**Comment by san-chang** [comment]
@holywyvern  Thanks a lot, this works for me.

**Comment by nemequ** [comment]
Sorry about the delayed response, I've been busy with some other stuff and had to take a step back from open source for a bit…

AFAICT this is the same issue as #30.  I'd love to ifdef around the issue, but I have no idea when it was fixed… if someone with more experience with mingw/msys/msys2 could figure this out I'd be happy to push a fix.
